apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-go-sample-multi-component-example-main-hvmx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-go-sample-multi-component-example-main-hvmx
    app.kubernetes.io/part-of: multi-component-application
  name: devfile-go-sample-multi-component-example-main-hvmx
  namespace: e2e-demo-cxke
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: devfile-go-sample-multi-component-example-main-hvmx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: devfile-go-sample-multi-component-example-main-hvmx
    spec:
      containers:
      - image: quay.io/mkovarik/test-images:7d5ef8afe445471e98af079e92ac8f1b
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
